"""Initial Migration

Revision ID: 45f86a3cc7dc
Revises:
Create Date: 2026-02-05 08:10:56.797035

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '45f86a3cc7dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categorymodel', ['id'])
    op.create_unique_constraint(None, 'foodcategorymodel', ['id'])
    op.create_unique_constraint(None, 'foodmodel', ['id'])
    op.create_unique_constraint(None, 'foodphotomodel', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'foodphotomodel', type_='unique')
    op.drop_constraint(None, 'foodmodel', type_='unique')
    op.drop_constraint(None, 'foodcategorymodel', type_='unique')
    op.drop_constraint(None, 'categorymodel', type_='unique')
    # ### end Alembic commands ###
