"""upgrade models

Revision ID: ce9d79731b62
Revises: 45f86a3cc7dc
Create Date: 2026-02-15 12:00:52.682102

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ce9d79731b62'
down_revision: Union[str, Sequence[str], None] = '45f86a3cc7dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_food_name'), 'food', ['name'], unique=False)
    op.drop_table('categorymodel')
    op.drop_table('foodmodel')
    op.drop_constraint(op.f('foodcategorymodel_food_id_fkey'), 'foodcategorymodel', type_='foreignkey')
    op.drop_constraint(op.f('foodcategorymodel_category_id_fkey'), 'foodcategorymodel', type_='foreignkey')
    op.create_foreign_key(None, 'foodcategorymodel', 'food', ['food_id'], ['id'])
    op.create_foreign_key(None, 'foodcategorymodel', 'category', ['category_id'], ['id'])
    op.alter_column('foodphotomodel', 'photo_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    op.drop_constraint(op.f('foodphotomodel_food_id_fkey'), 'foodphotomodel', type_='foreignkey')
    op.create_foreign_key(None, 'foodphotomodel', 'food', ['food_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'foodphotomodel', type_='foreignkey')
    op.create_foreign_key(op.f('foodphotomodel_food_id_fkey'), 'foodphotomodel', 'foodmodel', ['food_id'], ['id'])
    op.alter_column('foodphotomodel', 'photo_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'foodcategorymodel', type_='foreignkey')
    op.drop_constraint(None, 'foodcategorymodel', type_='foreignkey')
    op.create_foreign_key(op.f('foodcategorymodel_category_id_fkey'), 'foodcategorymodel', 'categorymodel', ['category_id'], ['id'])
    op.create_foreign_key(op.f('foodcategorymodel_food_id_fkey'), 'foodcategorymodel', 'foodmodel', ['food_id'], ['id'])
    op.create_table('foodmodel',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('foodmodel_pkey')),
    sa.UniqueConstraint('id', name=op.f('foodmodel_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('id', name=op.f('foodmodel_id_key1'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('categorymodel',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('categorymodel_pkey')),
    sa.UniqueConstraint('id', name=op.f('categorymodel_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('id', name=op.f('categorymodel_id_key1'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('name', name=op.f('categorymodel_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('slug', name=op.f('categorymodel_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_food_name'), table_name='food')
    op.drop_table('food')
    op.drop_table('category')
    # ### end Alembic commands ###
