FROM node:current-alpine3.23 AS react-build

WORKDIR /usr/app/

COPY ./package.json .

RUN npm i 

COPY ./src/web/ ./src/web/


RUN npm run build

FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY ./compose/nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=react-build /usr/app/src/web/dist/ usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]